# Generated by Django 3.2.7 on 2022-03-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watched',
            old_name='video_watched',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='watched',
            old_name='watched_time',
            new_name='time',
        ),
        migrations.AlterUniqueTogether(
            name='watched',
            unique_together={('owner', 'project')},
        ),
    ]
