# Generated by Django 3.2.7 on 2022-04-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220309_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views_24h',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
