# Generated by Django 3.2.7 on 2022-04-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_views_24h'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='movie_views',
        ),
        migrations.AddField(
            model_name='project',
            name='movie_views',
            field=models.ManyToManyField(blank=True, to='projects.ProjectViews'),
        ),
    ]
