# Generated by Django 3.2.7 on 2022-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220406_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='movie_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectViews',
        ),
    ]
