# Generated by Django 3.2.7 on 2022-04-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
