# Generated by Django 3.2.7 on 2022-04-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_genre_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='genre',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
