# Generated by Django 3.2.7 on 2022-04-19 23:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('projects', '0011_project_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='review',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.serie'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='watched',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.CreateModel(
            name='WatchedEpisode',
            fields=[
                ('time', models.IntegerField(blank=True, default=0, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('episode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.episode')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'unique_together': {('owner', 'episode')},
            },
        ),
    ]
