# Generated by Django 3.2.7 on 2022-04-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20220419_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
