# Generated by Django 3.2.7 on 2022-04-19 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='movie_views',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='episode',
            name='views_24h',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='views',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.episode'),
        ),
        migrations.AlterField(
            model_name='views',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
