# Generated by Django 3.2.7 on 2022-04-20 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20220419_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='progress',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
