# Generated by Django 3.2.7 on 2022-04-20 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_episode_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretTag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='secret_tags',
            field=models.ManyToManyField(blank=True, to='projects.SecretTag'),
        ),
    ]
