# Generated by Django 3.2.7 on 2022-05-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_auto_20220426_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='espisodes',
            field=models.ManyToManyField(blank=True, to='projects.Episode'),
        ),
        migrations.AddField(
            model_name='project',
            name='seasonal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
