# Generated by Django 3.2.7 on 2022-05-03 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20220502_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='espisodes',
            new_name='episodes',
        ),
    ]
